version: '3.7'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
      - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mariadb-data-volumes:/var/lib/mysql
    ports:
      - "3307:3306" # MariaDB Port
    container_name: mariadb

  redis-cache:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_cache.conf"]
    container_name: redis-cache

  redis-queue:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_queue.conf"]
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf.d:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_socketio.conf"]
    container_name: redis-socketio

  frappe:
    image: "jottun/frappe-docker-debian:1.0.0"
    build: .
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench:rw
      - ./conf/frappe:/home/frape/frappe-conf
    env_file:
      - conf/frappe/environment.env
    ports:
      - "80:8000" # Webserver Port
      - "443:443" # Webserver Port
      - "9000:9000" # Socketio Port
      - "6787:6787" # File Watcher Port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    container_name: frappe

volumes:
  mariadb-data-volumes: